spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/db-payment-service?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: dbadmin
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false # true apenas para testes
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true

app:
  jwt:
    secret: "${JWT_SECRET:change_this_secret_in_env}" # use @Value nas classes
    expiration-ms: 900000      # 15 min
    refresh-expiration-ms: 2592000000 # 30 dias
  integration:
    asaas:
      enabled: true
asaas:
  base-url: https://api-sandbox.asaas.com/v3
  api-key: ${ASAAS_API_KEY}
  timeout: 10000

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    tech.wgtecnologia.gateway: DEBUG
    org.springframework.security: DEBUG
